/*
 * generated by Xtext 2.10.0
 */
package hu.bme.mit.temalabor


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
